# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=6),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('Bus', 'Bus'), ('MicroBus', 'MicroBus'), ('Car', 'Car')], max_length=6),
        ),
    ]
