# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20170822_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionticketlog',
            name='driverId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.Driver'),
        ),
    ]
