# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 08:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0005_auto_20170822_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionticketlog',
            name='submitedUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
