# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_requisitionticketlog_submiteduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionticketlog',
            name='driverName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requisitionticketlog',
            name='vehicleId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle'),
        ),
        migrations.AddField(
            model_name='requisitionticketlog',
            name='vehicleNumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Free', 'Free'), ('InActive', 'InActive'), ('Booked', 'Booked')], max_length=8),
        ),
    ]
