# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_auto_20170823_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='driverId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.Driver'),
        ),
    ]
