# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_auto_20170824_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='driverId',
            new_name='driver_id',
        ),
        migrations.RenameField(
            model_name='requisitionticketlog',
            old_name='driverId',
            new_name='driver_id',
        ),
        migrations.RenameField(
            model_name='requisitionticketlog',
            old_name='driverName',
            new_name='driver_name',
        ),
        migrations.RenameField(
            model_name='requisitionticketlog',
            old_name='requisitionTicketLogId',
            new_name='requisitionTicketLog_id',
        ),
        migrations.RenameField(
            model_name='requisitionticketlog',
            old_name='vehicleId',
            new_name='vehicle_Id',
        ),
        migrations.RenameField(
            model_name='requisitionticketlog',
            old_name='vehicleNumber',
            new_name='vehicle_number',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='driverId',
            new_name='driver_id',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicleId',
            new_name='vehicle_id',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicleNumber',
            new_name='vehicle_number',
        ),
    ]
