# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 11:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0010_auto_20170824_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisitionticketlog',
            old_name='fromDateTime',
            new_name='from_date_time',
        ),
        migrations.RenameField(
            model_name='requisitionticketlog',
            old_name='ticketStatus',
            new_name='ticket_status',
        ),
        migrations.RenameField(
            model_name='requisitionticketlog',
            old_name='toDateTime',
            new_name='to_date_time',
        ),
        migrations.RemoveField(
            model_name='requisitionticketlog',
            name='submitedUser',
        ),
        migrations.AddField(
            model_name='requisitionticketlog',
            name='submited_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
