# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0011_auto_20170824_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionticketlog',
            name='passenger_number',
            field=models.IntegerField(default=1),
        ),
    ]
