# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 07:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0013_auto_20170906_0750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='type',
            new_name='vehicle_type',
        ),
    ]
